name: coffe_shop_gpt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  webview_flutter: ^4.7.0
  cached_network_image: ^3.3.1
  slide_to_act: ^2.0.2
 # carousel_slider:
 # card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
    android: "launcher_icon"    # Nama ikon untuk Android
    ios: true                   # Aktifkan untuk iOS
    image_path: "3assets/images/3pointcafe_logo.png" # GANTI DENGAN PATH LOGO ANDA

    # (Sangat Direkomendasikan untuk Android 8.0+) Konfigurasi Adaptive Icon
    adaptive_icon_background: "#FFFFFF" # Warna latar belakang ikon (misal: putih)
    adaptive_icon_foreground: "assets/images/3pointcafe_logo.png" # Logo tanpa background (hanya logo utamanya)